// ui/src/components/copy-block.tsx
import { Copy } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { copyToClipboard } from '@/lib/clipboard'
import { cn } from '@/lib/utils'

interface CopyBlockProps {
  text: string
  label?: string
  copiedLabel?: string
  className?: string
}

/**
 * A preformatted, copyable block of configuration text. The button sits outside
 * the scrolling <pre> so it never covers the content.
 */
export function CopyBlock({ text, label, copiedLabel = 'Kopiert', className }: CopyBlockProps) {
  return (
    <div className={cn('space-y-1.5', className)}>
      {label && (
        <p className="text-muted-foreground text-[11px] font-semibold tracking-wider uppercase">
          {label}
        </p>
      )}
      <div className="relative">
        <pre className="bg-muted/40 text-foreground max-h-80 overflow-auto rounded-lg border p-3 pr-11 font-mono text-xs leading-relaxed whitespace-pre-wrap [overflow-wrap:anywhere]">
          {text}
        </pre>
        <Button
          size="icon"
          variant="ghost"
          className="absolute top-1.5 right-1.5 size-7"
          onClick={() => copyToClipboard(text, copiedLabel)}
          aria-label="In die Zwischenablage kopieren"
        >
          <Copy className="size-3.5" />
        </Button>
      </div>
    </div>
  )
}

// ui/src/app/components/copy-block/copy-block.component.ts
import { Component, inject, input } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { CopyService } from '../../core/copy.service';

/** A preformatted, copyable block of configuration text. */
@Component({
  selector: 'app-copy-block',
  imports: [MatButtonModule, MatIconModule, MatTooltipModule],
  template: `
    @if (label()) {
      <p class="block-label muted">{{ label() }}</p>
    }
    <div class="block-wrap">
      <pre class="code-block">{{ text() }}</pre>
      <button
        mat-icon-button
        class="copy-button"
        type="button"
        matTooltip="In die Zwischenablage kopieren"
        (click)="copy.copy(text(), copiedLabel())"
      >
        <mat-icon>content_copy</mat-icon>
      </button>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }

      .block-label {
        margin: 0 0 6px;
        font-size: 12px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.04em;
      }

      /* The button lives outside the scrolling <pre> so it stays put. */
      .block-wrap {
        position: relative;
      }

      .copy-button {
        position: absolute;
        top: 4px;
        right: 4px;
        background: var(--bg-inset);
      }
    `,
  ],
})
export class CopyBlockComponent {
  readonly text = input.required<string>();
  readonly label = input<string>('');
  readonly copiedLabel = input<string>('Kopiert');

  protected copy = inject(CopyService);
}
